### ISSUE TITLE
TypeError: context.getScope is not a function

### ISSUE THREAD

**Issue by Opty1712** [aladdin-add/eslint-plugin#101]
**Tell us about your environment**
macos, node 18.18

* **eslint version: 9.14.0**
* **eslint-plugin-no-autofix version: 2.1.0**
* **eslint config**: 
```
{
    plugins: {
      'react-hooks': reactHooks,
      css: CSS,
      jest,
      'jest-dom': jestDOM,
      'react-memo': reactMemo,
      'unused-imports': unusedImports,
      'no-autofix': noAutofix,
    },
  }
  ```

**Expected behavior**
eslint works

**Actual behavior**
<img width="998" alt="image" src="https://github.com/user-attachments/assets/e7207adb-dee5-4b79-ba40-1d3c8349591b">

I've started to migrate project from 8.5 to 9x version, which requires FlatConfig, but stucked with this plugin

According to this article `that means the plugin has not yet been updated to use the new rules API` https://eslint.org/docs/latest/use/troubleshooting/v9-rule-api-changes

**Comment by aladdin-add** [comment]
you need to upgrade your tseslint to v8 to get eslint v9 support.

**Comment by Opty1712** [comment]
Thank you, it works now!
