### ISSUE TITLE
consider monorepo

### ISSUE THREAD

**Issue by aladdin-add** [aladdin-add/eslint-plugin#50]
to shared infra, it's nice to incorporate these repos:

+ [eslint-plugin-autofix](https://www.npmjs.com/package/eslint-plugin-autofix)
+ [eslint-plugin-no-autofix](https://www.npmjs.com/package/eslint-plugin-no-autofix)
+ [eslint-plugin-web](https://www.npmjs.com/package/eslint-plugin-web)

**Comment by aladdin-add** [comment]
cc @g-plane

**Comment by g-plane** [comment]
Agreed!
