### ISSUE TITLE
no-unused-var rule creates invalid code (3)

### ISSUE THREAD

**Issue by laurent22** [aladdin-add/eslint-plugin#58]
**Tell us about your environment**

* **eslint version:** 6.1.0
* **eslint-plugin-autofix version:** 0.0.8
* **eslint config:**

In this file:

	const { _ } = require('lib/locale.js');

	class OneDriveApi {

		async example() {
			throw new Error(_('oops'));
		}
	}

	module.exports = { OneDriveApi };

The rule replaces the require statement to:

    const {} = require('lib/locale.js');

Even though the underscore function is used in `throw new Error(_('oops'));`

**Comment by aladdin-add** [comment]
I was not able to repro the issue, see the commit https://github.com/aladdin-add/eslint-plugin/commit/a5687d2735702d28393c0a58ad191d2351e549a0

can you repro in the eslint demo page: https://eslint.org/demo, as we didn't modify the rule but adding a fixer.

**Comment by aladdin-add** [comment]
closing, as cannot be reproduced. please feel free to open a new issue if you encounter it again! :)
