### ISSUE TITLE
eslint-plugin-autofix bug - documentation update

### ISSUE THREAD

**Issue by stephen-dirtcreative** [aladdin-add/eslint-plugin#63]
**Tell us about your environment**

* **eslint version:**
6.8.0

* **eslint-plugin-autofix version:**
1.0.0

* **eslint config:**
relevant snip:
{...rules: [
  ...
  'autofix/no-unsafe-negation': 'error',
  ...
]}
**Expected behavior**
Rule defined

**Actual behavior**
Linter error for each file:
error  Definition for rule 'autofix/no-unsafe-negation' was not found  autofix/no-unsafe-negation

Triage performed:
If I understand the plugin code, it has a small set of custom rules it supplies, and then also defines all base eslint rules that have meta property 'fixable' that is true. Currently, eslint sets 'fixable' to null for 'no-unsafe-negation', and there is no custom rule in the autofix plugin. As a result, I would recommend removing 'no-unsafe-negation' from the documentation/README as a supported rule in autofix, or if it does work with specific versions of ESLint, add a note about that.

I don't use every supported rule autofix claims to support, but of the number of them I have configured, this is the only one that has this problem.

Thanks!

**Comment by aladdin-add** [comment]
emm... the fixer was removed in eslint v6.4.0 (https://github.com/eslint/eslint/pull/12157), and I forgot to update the readme somehow.

will update later, thanks! :)
