### ISSUE TITLE
[no-autofix] Exception issued in rules.js when running eslint checks

### ISSUE THREAD

**Issue by ababalau** [aladdin-add/eslint-plugin#72]
- eslint: 6.8.0
- eslint-plugin-json: 2.1.2
- eslint-plugin-json-format: 2.0.1
- eslint-plugin-no-autofix: 1.1.0
- .eslintrc:
............
"plugins": [
    "json",
    "no-autofix"
  ],
  "extends": "eslint:recommended",
  "rules": {
    "accessor-pairs": 0,
    "json/*": [
      "error",
      "allowComments"
    ],
    "array-bracket-spacing": [
      0,
      "never"
    ],
    "no-useless-catch": 1,
    "no-unused-labels": "off",
    "no-autofix/no-unused-labels": "warn"
  },
............
**Running**
> eslint . --fix
**Console output:**
TypeError: Failed to load plugin 'no-autofix' declared in '.eslintrc': Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/i336162/Projects/etd/etd-cloud-backend-services/node_modules/eslint-plugin-no-autofix/lib/rules.js:59:12
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/i336162/Projects/etd/etd-cloud-backend-services/node_modules/eslint-plugin-no-autofix/lib/rules.js:55:9)
    at Module._compile (/Users/i336162/Projects/etd/etd-cloud-backend-services/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/Users/i336162/Projects/etd/etd-cloud-backend-services/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! etd-cloud-backend-services@1.25.1 lint:dev: `eslint . --fix`
npm ERR! Exit status 2
npm ERR! 

This is due to one of the latest commit in rules.js (New: no-autofix support 3rd-party plugins):
- https://github.com/aladdin-add/eslint-plugin/commit/5efc9a38623b2309f298e711872e9fbcfa26cdd5#diff-1d1c2b3700f81f42414147cf48515b65ab47999913f58158295bfcac4415b885 

With this commit the following code was introduced in the rules.js:
"/ support 3rd-party plugins
// TODO: find a safer way, as this is no reliable(depends on the package manager)
const root = findUp.sync("package.json", { cwd: path.join(__dirname, "../../") });
const mdir = path.join(root, "../node_modules/");
const plugins = fs.readdirSync(mdir).filter(it => /^eslint-plugin/u.test(it));

plugins.forEach(it => {
    const plugin = require(it);
    const pluginName = it.replace(/^eslint-plugin-/u, "");

    Object.keys(plugin.rules).forEach(rule => {
        allRules[`${pluginName}/${rule}`] = getNonFixableRule(plugin.rules[rule]);
    });
});"

The **plugins** collection contains among others the plugin eslint-plugin-no-autofix itself, because it is installed in my ../node_modules directory.
Hence when plugin == eslint-plugin-no-autofix in the forEach loop, since there is no exposed array **rules** for the no-autofix plugin, I get the above exception

Best regards,
Adrian

**Comment by aladdin-add** [comment]
thanks for the detailed report, it should have been fixed in v1.1.1
