### ISSUE TITLE
no-autofix rules not working/not found with scoped packages

### ISSUE THREAD

**Issue by KimBum** [aladdin-add/eslint-plugin#77]
**Tell us about your environment**
- eslint version: 7.21.0
- eslint-plugin-no-autofix version: 1.1.2

Seems like the rule in itself is working (not 100% sure), but linter from i.e. vscode is still reporting "Definition for rule 'no-autofix/@typescript-eslint/explicit-member-accessibility' was not found."

Since I didn't see the TODO written in the code and my use case is exactly that, I am just opening this issue to hopefully track the status. Would be nice, if this is resolved at some point 😄 
https://github.com/aladdin-add/eslint-plugin/blob/dcb6993d6c377c5013051e4c894e90a49cda5e5b/packages/no-autofix/lib/rules.js#L51

**Comment by aladdin-add** [comment]
I'll look at this asap (maybe in a few days).

**Comment by abierbaum** [comment]
@aladdin-add Anything we can do to help?  I looked at the code and it seems like it should be possible but I don't understand the logic so well to make sure I would do it right.

**Comment by AndysonDK** [comment]
This should be reopened, I still have the same issue with:
eslint-plugin-no-autofix: ^1.2.0

**Comment by aladdin-add** [comment]
this should be fixed in [eslint-plugin-no-autofix v1.2.3](https://www.npmjs.com/package/eslint-plugin-no-autofix/v/1.2.3).

confirmed in a repo: https://github.com/aladdin-add/eslint-plugin-no-autofix-issue77 ( it was not easy to write tests for this ╮(￣▽￣)╭).
